/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i2 from '../../../../src/core/ngx-canvas-color-picker/ngx-canvas-color-picker';
export declare const RenderType_NgxCanvasColorPickerComponent: i0.RendererType2;
export declare function View_NgxCanvasColorPickerComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_NgxCanvasColorPickerComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const NgxCanvasColorPickerComponentNgFactory: i0.ComponentFactory<i2.NgxCanvasColorPickerComponent>;
